// <auto-generated />
using System;
using System.Text.Json;
using Jetstream.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jetstream.Migrations
{
    [DbContext(typeof(JetDbContext))]
    partial class JetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jetstream.Data.Model.JetDbGateway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gateway");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0202ce66-2504-4211-ba35-bce32e527d41"),
                            Created = new DateTime(2022, 7, 25, 14, 0, 59, 687, DateTimeKind.Local).AddTicks(3542),
                            Description = "Accepts task objects and prototypes data around due dates. ",
                            Name = "Sample Task Gateway"
                        });
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbGatewayProto", b =>
                {
                    b.Property<Guid>("GatewayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProtoId")
                        .HasColumnType("uuid");

                    b.HasKey("GatewayId", "ProtoId");

                    b.HasIndex("ProtoId");

                    b.ToTable("GatewayProto");

                    b.HasData(
                        new
                        {
                            GatewayId = new Guid("0202ce66-2504-4211-ba35-bce32e527d41"),
                            ProtoId = new Guid("d8c81623-0fd2-49c0-9e09-43242c962996")
                        });
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbKind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kind");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4e3c63f-78b0-4382-a434-a00d9d3e61f9"),
                            Name = "Due Date",
                            Namespace = "Jetstream.Core"
                        });
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbProto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Expression")
                        .HasColumnType("text");

                    b.Property<Guid>("KindId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KindId");

                    b.ToTable("Proto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8c81623-0fd2-49c0-9e09-43242c962996"),
                            Expression = "$.Date",
                            KindId = new Guid("b4e3c63f-78b0-4382-a434-a00d9d3e61f9"),
                            Name = "Task Due Date",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Contents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GatewayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GatewayId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbUnitProtoKind", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProtoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KindId")
                        .HasColumnType("uuid");

                    b.HasKey("UnitId", "ProtoId", "KindId");

                    b.HasIndex("KindId");

                    b.HasIndex("ProtoId");

                    b.ToTable("UnitKind");
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbGatewayProto", b =>
                {
                    b.HasOne("Jetstream.Data.Model.JetDbGateway", "Gateway")
                        .WithMany()
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jetstream.Data.Model.JetDbProto", "Proto")
                        .WithMany()
                        .HasForeignKey("ProtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");

                    b.Navigation("Proto");
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbProto", b =>
                {
                    b.HasOne("Jetstream.Data.Model.JetDbKind", "Kind")
                        .WithMany()
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kind");
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbUnit", b =>
                {
                    b.HasOne("Jetstream.Data.Model.JetDbGateway", "Gateway")
                        .WithMany()
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("Jetstream.Data.Model.JetDbUnitProtoKind", b =>
                {
                    b.HasOne("Jetstream.Data.Model.JetDbKind", "Kind")
                        .WithMany()
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jetstream.Data.Model.JetDbProto", "Proto")
                        .WithMany()
                        .HasForeignKey("ProtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jetstream.Data.Model.JetDbUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kind");

                    b.Navigation("Proto");

                    b.Navigation("Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
